# -*- coding: utf-8 -*-
"""email_spam_or_not.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LCxoQ64TPhp39HSk5nTBaHQqm7F7t7a
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df=pd.read_csv('/content/mail_data.csv')

df.head()

data=df.where((pd.notnull(df)),'')

data.head()

data.loc[data['Category']=='spam','Category',]=0
data.loc[data['Category']=='ham','Category',]=1

data.head()

x=data['Message']
y=data['Category']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=3)

feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

x_train_features = feature_extraction.fit_transform(x_train)
x_test_features = feature_extraction.transform(x_test)
y_train=y_train.astype('int')
y_test=y_test.astype('int')

model=LogisticRegression()

model.fit(x_train_features,y_train)

x_train_pred=model.predict(x_train_features)
accuracy=accuracy_score(x_train_pred,y_train)
print(accuracy)

x_test_pred=model.predict(x_test_features)
accuracy=accuracy_score(x_test_pred,y_test)
print(accuracy)

input_mail=["Nah I don't think he goes to usf, he lives around here though"]
feature_mail=feature_extraction.transform(input_mail)
pred=model.predict(feature_mail)
print(pred)
if pred[0]==1:
   print('ham mail')
else:
  print('spam mail')

