# -*- coding: utf-8 -*-
"""credit_card_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maB_Oq3xnO1HKsxSWDUGGBzj5_s_ctn2
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,recall_score,f1_score

df=pd.read_csv('/content/application_data.csv')

df.head()

df.isnull().sum()

#for col in df.columns:
  #  df[col] = pd.to_numeric(df[col], errors='coerce')


#df.fillna(df.mean(),inplace=True)
df.dropna(inplace=True)
df.head()

df=pd.get_dummies(df)

df.head()

x=df.drop('TARGET',axis=1)
y=df['TARGET']

scaler=StandardScaler()
x=scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

model=RandomForestClassifier()
model.fit(x_train,y_train)

pred=model.predict(x_train)
print(accuracy_score(y_train,pred))
print(recall_score(y_train,pred))
print(f1_score(y_train,pred))



