# -*- coding: utf-8 -*-
"""alzheimers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVueG39uLXu-cI3ocTHYxbWd_9rRboDX
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df=pd.read_csv('/content/alzheimers_disease_patient_data.csv')

df.head()

x=df.drop(['Diagnosis','DoctorInCharge'],axis=1)
y=df['Diagnosis']

print(x.shape)

scaler=StandardScaler()

scaler.fit(x)
data=scaler.transform(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)
model=LogisticRegression()

model.fit(x_train,y_train)

train=model.predict(x_train)
train_acc=accuracy_score(train,y_train)
print(train_acc)

test=model.predict(x_test)
test_acc=accuracy_score(test,y_test)
print(test_acc)

input_data = ()
numpy = np.asarray(input_data)
reshape = numpy.reshape(1, -1)
std = scaler.transform(reshape)
pred = model.predict(std)
print(pred)